version: '3.8'

services:
  web-app:
    build:
      dockerfile: "Dockerfile.base"
    working_dir: /app/
    ports:
      - "$DOCKER_COMPOSE_WEB_APP_PORT:8000"
    volumes:
      - ./app:/app
    env_file: ".env"
    command: "uvicorn main:app --host 0.0.0.0 --reload"